name: Davide Madrisan
description: My Personal Website and Blog with articles about science and technology
google_analytics: G-8QWNT8ZCPM
images:
  blog:
    default: /assets/images/blog-default.jpg
    defaultsquared: /assets/images/blog-default-squared.jpg
  favicon: /assets/images/favicon-32x32.png
  home: /assets/images/main-mountains.jpg
kramdown:
  hard_wrap: false
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
markdown: kramdown
permalink: /blog/:categories/:year-:month-:day/:title
plugins:
  - jemoji
  - jekyll-redirect-from
socials:
  facebookappid: '383695016267763'
  github: https://github.com/madrisan
  linkedin: https://www.linkedin.com/in/madrisan
  stackoverflow: https://stackoverflow.com/users/5721620/davide-madrisan
  twitter: https://twitter.com/dmadrisan
  twitterid: '@dmadrisan'
sources:
  bootstrap:
    css:
      href: 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css'
      integrity: 'sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3'
    icons:
      href: 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css'
    js:
      href: 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js'
      integrity: 'sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p'
  fontawesome: 'https://kit.fontawesome.com/31fa09e3cc.js'
  highcharts:
    js: 'https://code.highcharts.com/highcharts.js'
    modules:
      accessibility: 'https://code.highcharts.com/modules/accessibility.js'
      exporting: 'https://code.highcharts.com/modules/exporting.js'
  jquery: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js'
  mathjax: 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
timezone: Europe/Paris
url: https://madrisan.github.io
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
