name: Davide Madrisan
description: My Personal Website and Blog with articles about science and technology
images:
  blog:
    default: /assets/images/blog-default.jpg
    defaultsquared: /assets/images/blog-default-squared.jpg
  favicon: /assets/images/favicon-32x32.png
  home: /assets/images/main-mountains.jpg
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jemoji
socials:
  facebookappid: '383695016267763'
  github: https://github.com/madrisan
  linkedin: https://www.linkedin.com/in/madrisan
  stackoverflow: https://stackoverflow.com/users/5721620/davide-madrisan
  twitter: https://twitter.com/dmadrisan
  twitterid: '@dmadrisan'
sources:
  bootstrap:
    css: 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css'
    js: 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js'
  fontawesome: 'https://kit.fontawesome.com/31fa09e3cc.js'
  highcharts:
    js: 'https://code.highcharts.com/highcharts.js'
    modules:
      accessibility: 'https://code.highcharts.com/modules/accessibility.js'
      exporting: 'https://code.highcharts.com/modules/exporting.js'
  jquery: 'https://cdn.bootcss.com/jquery/3.5.1/jquery.min.js'
  mathjax: 'https://cdn.bootcss.com/mathjax/2.7.9/MathJax.js?config=TeX-MML-AM_CHTML'
  popper: 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.6.0/umd/popper.min.js'
url: https://madrisan.github.io
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
