name: Davide Madrisan, personal website
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll_social_icons
  - jemoji
socials:
  github: https://github.com/madrisan
  linkedin: https://www.linkedin.com/in/madrisan
  twitter: https://twitter.com/dmadrisan
