name: build gh-pages
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.2', '4.0']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ./script/bootstrap
    - run: ./script/cibuild
